----- examen adea 
  CREATE TABLE ADEA(
ID NUMBER PRIMARY KEY,
CLIENTE NVARCHAR2(50),
APELLIDO_PATERNO NVARCHAR2(50),
APELLIDO_MATERNO NVARCHAR2(50),
EMAIL NVARCHAR2(50),
FECHAALTA DATE,
FECHABAJA DATE,
STATUS NVARCHAR2(1),
FECHAREVOCADO DATE,
FECHA_VIGENCIA DATE,
AREA NUMBER,
FECHAMODIFICACION DATE
);
INSERT INTO ADEA VALUES(1,'Gris','Garcia','lorenoz','gris@gmail.com','02/02/2023','25/03/2022','A','31/03/2022','30/01/2021',1,'17/05/2022');
COMMIT;
 SELECT * FROM ADEA;
 delete  FROM ADEA where id=2;
 
---- CONTRASEÑAS 
CREATE TABLE contrasena(
ID NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(50),
PASSWORD NVARCHAR2(100)
);
drop table contrasena;
select * from contrasena; 
COMMIT;